# Generated by Django 5.2.4 on 2025-07-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='concluido',
        ),
    ]
