# Generated by Django 5.2.4 on 2025-07-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_tarefa_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
